//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileHelperAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatFileDetail
    {
        public long Id { get; set; }
        public string DatName { get; set; }
        public int LocationId { get; set; }
        public string FullFilePath { get; set; }
        public Nullable<long> Size { get; set; }
        public string MD5Hash { get; set; }
        public string CRC32 { get; set; }
        public string SHA256 { get; set; }
        public Nullable<System.DateTime> LastAccessTime { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastWriteTime { get; set; }
        public bool Available { get; set; }
        public Nullable<System.DateTime> LastCheckedTime { get; set; }
    }
}
