//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RvInstanceAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RvInstance
    {
        public int Id { get; set; }
        public string RvLocation { get; set; }
        public Nullable<int> DatDescriptionID { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> ConfigLastUpdated { get; set; }
        public string DatRootLocation { get; set; }
        public Nullable<System.DateTime> DatRootLastUpdated { get; set; }
        public string CacheFileLocation { get; set; }
        public Nullable<System.DateTime> CacheFileLastUpdated { get; set; }
        public Nullable<System.DateTime> ReportLastUpdated { get; set; }
        public string ScanLevel { get; set; }
        public string FixLevel { get; set; }
        public bool CopyFixDats { get; set; }
        public bool CollectStats { get; set; }
        public bool Active { get; set; }
        public Nullable<int> DatCategoryId { get; set; }
        public Nullable<bool> DatWatch { get; set; }
    }
}
